services:
    splash:
        image: "scrapinghub/splash"
        networks:
            - backend-net
        ports:
            - "8050:8050"
    scraper:
        build: "scraper"
        networks:
            - backend-net
        ports:
            - "6023:6023"
        volumes: 
            - ./scraper:/code
    web:
        build: "web"
        restart: always
        networks:
            - frontend-net
        ports: 
            - "5000:5000"
        volumes: 
            - ./web/src:/code
    db:
        image: "mysql"
        command: "--default-authentication-plugin=mysql_native_password"
        restart: always
        networks:
            - backend-net
            - frontend-net
        volumes:
            - db-data:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=example
            - MYSQL_ROOT_PASSWORD=password
volumes:
    db-data:
networks:
    backend-net:
    frontend-net:
