version: "3"
services:
    splash:
        image: scrapinghub/splash
        container_name: splash
        ports:
            - "8050:8050"
        labels:
            kompose.service.type: loadbalancer
    scraper:
        image: scraper
        container_name: scraper
        restart: on-failure