apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: loadbalancer
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: splash
  name: splash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: splash
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: loadbalancer
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: splash
    spec:
      containers:
        - image: scrapinghub/splash
          name: splash
          ports:
            - containerPort: 8050
          resources: {}
      restartPolicy: Always
status: {}
