apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: loadbalancer
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: splash
  name: splash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: splash
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: loadbalancer
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: splash
    spec:
      containers:
        - image: scrapinghub/splash
          name: splash
          ports:
            - containerPort: 8050
          command: ["python3", "/app/bin/splash", "--max-timeout", "3600", "--proxy-profiles-path", "/etc/splash/proxy-profiles", "--js-profiles-path", "/etc/splash/js-profiles", "--filters-path", "/etc/splash/filters", "--lua-package-path", "/etc/splash/lua_modules/?.lua"]
          resources: {}
      restartPolicy: Always
status: {}
