FROM python:3.9-slim

#Set the working directory
WORKDIR /code

# Copy requirements.txt first
COPY requirements.txt .

# Install all the dependencies
RUN pip install -r requirements.txt

#copy all the files
COPY src/ .

# Direct to Flask app
ENV FLASK_APP=main.py

#Expose the required port
EXPOSE 8080

#Run the command
# NOTE: '--host=0.0.0.0' is only being used to expose Flask outside Docker.
# I'm not sure whether we will need to keep that command in.
CMD ["gunicorn", "-w", "2", "--bind", "0.0.0.0:8080", "wsgi:app"]